  // script.js
const container = document.getElementById('list-lh');
const searchInput = container.querySelector('#search-lh');
const categoryFilter = container.querySelector('#category-filter-lh');
const itemList = container.querySelector('#itemList_LH');

// Mapping display names
const categoryLabels = {
  KiemHiep: 'Tiên Hiệp',
  TrinhTham: 'Trinh Thám',
  LinhDi: 'Linh Dị',
  XuyenKhong: 'Xuyên Không',
  TamLyHoc: 'Tâm Lý Học',
  KyNangSong: 'Kỹ Năng Sống',
  QuanTri: 'Quản Trị',
  KinhTeTaiChinh: 'Kinh Tế - Tài Chính',
  VienTuong: 'Viễn Tưởng'
};

const items = [
  { name: 'Án Mạng Trong Vô Thức - Melinda Leigh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1AdAzrI002vnTTcOwkAT4xw', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/04/cover-62.jpg' },
  { name: 'Hồ Sơ Tâm Lý Tội Phạm Tập 1 - Cương Tuyết Ấn', category: 'TrinhTham', url: 'https://1024terabox.com/s/1Js8a_NorDGytQJ37_ePKLQ', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/Ho-So-Tam-Ly-Pham-Toi-Cuong-Tuyet-An.jpg' },
  { name: 'Hồ Sơ Tâm Lý Tội Phạm Tập 2 - Cương Tuyết Ấn', category: 'TrinhTham', url: 'https://1024terabox.com/s/1dRjOKHlQmi63JFTHcOI6wg', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/04/cover-59.jpg' },
  { name: 'Trộm Mệnh Đôi Cá Âm Dương Tập 1 – Du Hồn Nhập Mộng', category: 'LinhDi', url: 'https://1024terabox.com/s/1lkf4Kvi_qWIUH6s2ZiK57Q', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/04/doi-ca-am-duong-du-hon-nhap-mong-nhat-mai-dong-tien-han-vu-phi-dich.jpg' },
  { name: 'Trộm Mệnh Lư Hương Ngư VănTập 2 – Chu Sa Chỉ Lối', category: 'LinhDi', url: 'https://1024terabox.com/s/1WSdOfvTrQMnvroe-YNPp3Q', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/04/trom-menh-nhat-mai-dong-tien.jpg' },
  { name: 'Minh Hôn Với Quỷ - Ninh Thư', category: 'LinhDi', url: 'https://1024terabox.com/s/1Km-QpIbD-dNA2Xo5CtYaHg', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/02/minh-hon-voi-quy-ninh-thu.jpg' },
  { name: 'Bảo Tàng Sơn Hải - Đạo Môn Lão Cửu', category: 'LinhDi', url: 'https://1024terabox.com/s/1UL4kOwXu6GZLzuL6ZvD8AA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/02/bao-tang-son-hai-dao-mon-lao-cuu.jpg' },
  { name: 'Người Vớt Xác - Trần Thập Tam', category: 'LinhDi', url: 'https://1024terabox.com/s/1wCNAUT6e6uS5GRB1zpys_A', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/02/nguoi-vot-xac-tran-thap-tam.jpg' },
  { name: '14 Ngày Đẫm Máu - Jeremy Bates', category: 'LinhDi', url: 'https://1024terabox.com/s/1k0urfHrmgrdNTPB1yl2E1w', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/04/cover-9.jpg' },
  { name: 'Người Điều Khiển Mê Cung - Donato Carrisi', category: 'TrinhTham', url: 'https://1024terabox.com/s/1wm75ScPGFK0MHk17Sdi1kg', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/12/Nguoi-Dieu-Khien-Me-Cung.jpg' },
  { name: '19 Năm Mưu Sát – Tập 1 - Na Đa', category: 'TrinhTham', url: 'https://1024terabox.com/s/1r2QZM-6Ndf320EmobbBW7Q', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/07/19-Nam-Muu-Sat-Tap-1.jpg' },
  { name: '19 Năm Mưu Sát – Tập 2 - Na Đa', category: 'TrinhTham', url: 'https://1024terabox.com/s/118_UN6dO4NpG7NChU8V1eA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/08/19-Nam-Muu-Sat-Tap-2.jpg' },
  { name: 'Trái Tim Của Quỷ - Mahokaru Numata', category: 'TrinhTham', url: 'https://1024terabox.com/s/1TLdkTuJWV4jSOLT0TblCBQ', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/08/Trai-Tim-Cua-Quy.jpg' },
  { name: 'Tội Ác Sau Những Bức Tranh - Jason Rekulak', category: 'TrinhTham', url: 'https://1024terabox.com/s/1__Jq6roYqwkxrB_CoaLeug', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/08/Toi-Ac-Sau-Nhung-Buc-Tranh.jpg' },
  { name: 'Những Vụ Án Kỳ Bí - Diêm Bắc Lão Cửu', category: 'TrinhTham', url: 'https://1024terabox.com/s/1kpbwC6zBHuGIsGPT_1b8OQ', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/08/nhung-vu-an-ky-bi-diem-bac-lao-cuu.jpg' },
  { name: 'Người Gác Đêm 1 - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1m7qBAhrR89yQkr0sHnCGCQ', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/nguoi-gac-dem-tan-minh.jpg' },
  { name: 'Người Gác Đêm 2 - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1EpkKvfwBgZfV--9sGOndtA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/nguoi-gac-dem-tap-2-tan-minh-trang-duong-dich.jpg' },
  { name: 'Người Gác Đêm 3 - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1jt0DMX7FmkDPbkYfhLeNRA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/nguoi-gac-dem-tap-3-tan-minh-nguyen-quynh-trang-dich.jpg' },
  { name: 'Người Gác Đêm 4 - Đại Kết Cục - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1T6seFUdTIFm9xxmEtEyWdA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/05/Nguoi-Gac-Dem-tap-4.jpg' },
  { name: 'Pháp y Tần Minh 1 Người Giải Mã Tử Thi - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/15kwNNqB_epR1TDiiM2z6mg', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/36721769162_bd85043a29_o.jpg' },
  { name: 'Pháp y Tần Minh 2 Lời Tố Cáo Thầm Lặng - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1elyFjiNyGBWGYXsv8OvvZA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/39352622462_80b8275e2c_o.jpg' },
  { name: 'Pháp y Tần Minh 3 Ngón Tay Thứ Mười Một - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1XLnOpDucF12ETGEOGtCZgg', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/39352622382_01de8ec01f_o.jpg' },
  { name: 'Pháp y Tần Minh 4 Kẻ Dọn Rác - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1rEnX1RHzdCgq9dsMBFUacg', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/ke-don-rac-tan-minh.jpg' },
  { name: 'Pháp y Tần Minh 5 Người Sống Sót - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1prBSSnXOMTDT1yh_Y3njtA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/nguoi-song-sot-tan-minh.jpg' },
  { name: 'Pháp y Tần Minh 6 Kẻ Nhìn Trộm - Tần Minh', category: 'TrinhTham', url: 'https://1024terabox.com/s/1byLnYJDvNnU3gG4rXAwS2A', imageUrl: 'https://ebookvie.com/wp-content/uploads/2023/12/ke-nhin-trom-tan-minh.jpg' },
  { name: 'Trạm Tín Hiệu Số 23 - Hugh Howey', category: 'VienTuong', url: 'https://1024terabox.com/s/1IuE467rFdfJrHok4pFJ73Q', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/04/Tram-Tin-Hieu-So-23.jpg' },
  { name: 'Thú Trấn Mộ - Sái Tuấn', category: 'LinhDi', url: 'https://1024terabox.com/s/1Gv3qUZQfMCcf9TEXW6QMcA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/02/thu-tran-mo-sai-tuan.jpg' },
  { name: 'Cái Chết Của Những Xác Sống – Tập 1 - Masaya Yamaguchi', category: 'TrinhTham', url: 'https://1024terabox.com/s/1p430bTNVCKuueqkb2IlM8w', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/04/cai-chet-cua-nhung-xac-song-tap-1-masaya-yamaguchi-trinh-thanh-tam-dich.jpg' },
  { name: 'Cái Chết Của Những Xác Sống – Tập 2 - Masaya Yamaguchi', category: 'TrinhTham', url: 'https://1024terabox.com/s/1lOy7w82xgMjSXPCao25puA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/04/cai-chet-cua-nhung-xac-song-tap-2-masaya-yamaguchi-vo-phuong-ngan-dich.jpg' },
  { name: 'Đừng Bao Giờ Nói Dối - Freida McFadden', category: 'TrinhTham', url: 'https://1024terabox.com/s/1Ee1h_D2fR0jskbc7u8xZuQ', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/04/cover.jpg' },
  { name: 'Núi Chuột Quét - Hô Diên Vân', category: 'TrinhTham', url: 'https://1024terabox.com/s/1Co049_BgTsryMLjoOxI_lA', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/12/Nui-Chuot-Quet.jpg' },
  { name: 'Hung Trạch - Tập 2 - Hô Diên Vân', category: 'LinhDi', url: 'https://1024terabox.com/s/1c5LoLL6KIweQ8gDGT2CcMw', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/02/hung-trach-tap-2-ho-dien-van-tu-huynh-dich.jpg' },
  { name: 'Hung Trạch - Tập 1 - Hô Diên Vân', category: 'LinhDi', url: 'https://1024terabox.com/s/1w81sZV5QYpVQ_liPtHSQ_g', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/12/hung-trach-tap-1-ho-dien-van-tu-huynh-dich.jpg' },  
  { name: 'Biến Mọi Thứ Thành Tiền - Nguyễn Anh Dũng', category: 'KinhTeTaiChinh', url: 'https://1024terabox.com/s/1j2dda_gshYew4A9F0d994A', imageUrl: 'https://ebookvie.com/wp-content/uploads/2024/04/Bien-Moi-Thu-Thanh-Tien.jpg' },
  { name: 'Mô Hình Chất Lượng Dịch Vụ Trong Bán Lẻ - TS. Đào Xuân Khương', category: 'KinhTeTaiChinh', url: 'https://1024terabox.com/s/1TimeqQEiJ6CDxuz8DtB9wg', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/06/mo-hinh-chat-luong-dich-vu-trong-ban-le-ts-dao-xuan-khuong.jpg' },
  { name: 'Kỳ Án Pháp Y 2: Truy Tìm Bằng Chứng – Lời Thì Thầm Của Tử Thi - Lục Ngoạn', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ky-an-phap-y-tap-2-truy-tim-bang-chung-loi-thi-tham-cua-tu-thi.jpg' },
  { name: 'Án Mạng Vùng Lưỡng Hà - Agatha Christie', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/an-mang-vung-luong-ha.jpg' },
  { name: 'Hõm Chết – David Baldacci', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/hom-chet.jpg' },
  { name: 'Ngôi Nhà Muôn Cánh Cửa - Tan Twan Eng', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ngoi-nha-muon-canh-cua.jpg' },
  { name: 'Báo Thù – Mười Một Câu Chuyện Tăm Tối - Ogawa Yoko', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/bao-thu-muoi-mot-cau-chuyen-tam-toi.jpg' },
  { name: 'Tàng Long Quyết - Thân Thị Sơn Nhân', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/tang-long-quyet.jpg' },
  { name: 'Truy Đuổi Khói Tuyết - Higashino Keigo', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/truy-duoi-khoi-tuyet.jpg' },
  { name: 'Vũ Điệu Cuồng Phong - Higashino Keigo', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/vu-dieu-cuong-phong.jpg' },
  { name: 'Sát Nhân Trong Chiếc Hộp Mắt Ma - Masahiro Imamura', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/sat-nhan-trong-chiec-hop-mat-ma.jpg' },
  { name: 'Đêm Định Mệnh Ở Barcelona - Cornell Woolrich', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/dem-dinh-menh-o-barcelona.jpg' },
  { name: 'Kẻ Khác – Guillaume Musso', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ke-khac.jpg' },
  { name: 'Phân Tích Hành Vi Phạm Tội - Moriarty K', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/phan-tich-hanh-vi-pham-toi-giai-ma-ky-an-the-gioi.jpg' },
  { name: 'Tấm Gương Nứt Vỡ - Agatha Christie', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/tam-guong-nut-vo.jpg' },
  { name: 'Quỷ Tiết – Hồng Nương Tử', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/quy-tiet.jpg' },
  { name: 'Bảy Ngày Chờ Chết - Holly Jackson', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/bay-ngay-cho-chet.jpg' },
  { name: 'Ma Trùng – Chan Ho-Kei', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ma-trung.jpg' },
  { name: 'Ván Cược – Oh Yoon-Hee', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/van-cuoc.jpg' },
  { name: 'Thám Tử Thứ Tám - Alex Pavesi', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/tham-tu-thu-tam.jpg' },
  { name: 'Chết Chùm – Donald Goines', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/chet-chum.jpg' },
  { name: 'Bù Nhìn – Kim Lăng Vân', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/bu-nhin.jpg' },
  { name: 'Bảy Ngày Phán Quyết - Kōtarō Isaka', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/bay-ngay-phan-quyet.jpg' },
  { name: 'Rượu Độc – Higashino Keigo', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ruou-doc.jpg' },
  { name: 'Két “Xác” – Hideo Yokoyama', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ket-xac.jpg' },
  { name: 'Ác Não – Long Vĩ Bình', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ac-nao.jpg' },
  { name: 'Kéo Búa Bao – Alice Feeney', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/keo-bua-bao.jpg' },
  { name: 'Danh Sách Trả Thù - Jack Carr', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/danh-sach-tra-thu.jpg' },
  { name: 'Vương Quốc Tội Lỗi - Jo Nesbø', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/vuong-quoc-toi-loi.jpg' },
  { name: 'Không Thành Kế – Hô Diên Vân', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/khong-thanh-ke.jpg' },
  { name: 'Bạn Trai – Freida McFadden - Freida McFadden', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ban-trai.jpg' },
  { name: 'Người Phụ Nữ Lừa Cả Thế Giới - Beau Donelly, Nick Toscano', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/nguoi-phu-nu-lua-ca-the-gioi.jpg' },
  { name: 'Kỳ Án Bảy Mặt Đồng Hồ - Agatha Christie', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ky-an-bay-mat-dong-ho.jpg' },
  { name: 'Bí Mật Của Thiên Thần - Guillaume Musso', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/bi-mat-cua-thien-than.jpg' },
  { name: 'Oan Hồn Băng Cốc - A Sửu', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/oan-hon-bang-coc.jpg' },
  { name: 'Hợp Táng Án - Na Đa', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/hop-tang-an.jpg' },
  { name: 'Chiếc Xe Màu Tím – Tuyển Tập Truyện Ma Edith Nesbit - Edith Nesbit', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/chiec-xe-mau-tim-tuyen-tap-truyen-ma-edith-nesbit.jpg' },
  { name: 'Tiếng Thét Dưới Băng - Camilla Grebe', category: 'TrinhTham', url: '#', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/tieng-thet-duoi-bang-camilla-grebe-26-nguyen-thi-tuoi-dich.jpg' },
  { name: 'Khúc Xương Biết Hát - R. Austin Freeman', category: 'TrinhTham', url: 'https://1024terabox.com/s/1m9zSeKItJU97juQ7IEARnw', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/khuc-xuong-biet-hat-r-austin-freeman-26-xuan-sinh-dich.jpg' },
  { name: 'Bàn Tay Đen - Arthur B. Reeve', category: 'TrinhTham', url: 'https://1024terabox.com/s/1Wvzzgdrmb9k1gl3r4UVC6w', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ban-tay-den-arthur-b-reeve-26-phi-yen-dich.jpg' },
  { name: 'Cô Gái Đến Từ Milan - Giorgio Scerbanenco', category: 'TrinhTham', url: 'https://1024terabox.com/s/1hWnLGzkDfQwWBoJqlRaBdQ', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/co-gai-den-tu-milan-giorgio-scerbanenco-26-mai-trang-dich.jpg' },
  { name: 'Kẻ Chủ Mưu - Shari Lapena', category: 'TrinhTham', url: 'https://1024terabox.com/s/1toaeQI_Op0zMV8Pp42-DBQ', imageUrl: 'https://ebookvie.com/wp-content/uploads/2025/10/ke-chu-muu-shari-lapena-26-orkid-dich.jpg' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' },
  { name: '#', category: 'TrinhTham', url: '#', imageUrl: '#' }
];

function renderList(listItems) {
  itemList.style.display = 'grid';
  itemList.innerHTML = '';
  listItems
    .filter(item => item.url && item.url !== '#')
    .sort((a, b) => a.name.localeCompare(b.name, 'vi'))
    .forEach(item => {
      const li = document.createElement('li');
      const link = document.createElement('a');
      link.className = 'item-name';
      link.textContent = item.name;
      link.onclick = () => window.open(item.url, '_blank');

      const img = document.createElement('img');
      img.src = item.imageUrl;
      img.alt = item.name;
      img.className = 'item-image';

      const cat = document.createElement('span');
      cat.className = `category ${item.category}`;
      cat.textContent = categoryLabels[item.category];

      li.appendChild(img);
      li.appendChild(link);
      li.appendChild(cat);
      itemList.appendChild(li);
    });
}

function filterAndRender() {
  const keyword = searchInput.value.toLowerCase();
  const sel = categoryFilter.value;
  let filtered = items;
  if (sel !== 'all') filtered = filtered.filter(i => i.category === sel);
  if (keyword) filtered = filtered.filter(i =>
    i.name.toLowerCase().includes(keyword) ||
    categoryLabels[i.category].toLowerCase().includes(keyword)
  );
  renderList(filtered);
}

searchInput.addEventListener('input', filterAndRender);
categoryFilter.addEventListener('change', filterAndRender);
filterAndRender();
